# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyBaMM Twitter bot

on:
  push:
    
  pull_request:

  # everyday at 3 am UTC
  schedule:
    - cron:  '*/30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybamm
    - name: Run unit tests
      run: |
        pip install flake8 pytest wheel
        python -m unittest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install git+https://github.com/pybamm-team/PyBaMM@develop
        pip install jax==0.1.75 jaxlib==0.1.52
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         files: ./coverage1.xml,./coverage2.xml
#         directory: ./coverage/reports/
#         flags: unittests
#         env_vars: OS,PYTHON
#         name: codecov-umbrella
#         fail_ci_if_error: true
#         path_to_write_report: ./coverage/codecov_report.txt
#         verbose: true
